### PR TITLE
scale by log10(exp(1)) for log10 plots

### PR DESCRIPTION
**Pull request by evanbiederstedt**
Attempt to address the following issue: https://github.com/kharchenkolab/pagoda2/issues/51

I started looking into the units...and it's true that the plot is currently plotting in natural log scale, not log10(). 

This PR scales the plot values such that `adjustVariance` plots in log10. Note calculations for over-dispersed genes, etc. are still log()-based. 

That is, I don't touch this

```
ods <- order(df$v,decreasing=TRUE); if(length(ods)>1e3) { ods <- ods[1:1e3] }
...
if(use.unadjusted.pvals) {
    ods <- which(df$lp<log(alpha))     ## pf() from stats (the F-distribution)  uses log()
} else {
    ods <- which(df$lpa<log(alpha))   ## df$lpa is based on log()-based BH adjustments, bh.adjust()
 }
```
or this
```
vi <- which(is.finite(df$v) & df$nobs>=min.gene.cells);
```

I'm simply making sure that what was plotted previously is now log10-scaled. 

The resulting plot from the [walkthrough](https://github.com/kharchenkolab/pagoda2/blob/master/vignettes/pagoda2.walkthrough.oct2018.md) looks like the following:

log10_plot

where it previously was the following:
original

### CODE REVIEW

**Comment by VPetukhov** [comment]
I don't see why it can't be log10... @pkharchenko, do you have any ideas?

**Comment by pkharchenko** [comment]
let’s leave this one for now - just change the axes on the plot. You can, of course move everything to log10, but doing this without introducing mistakes in calculations takes a bit of care. And there’s no real reason to do this - for calculations it’s more standard to use log/exp.

**Comment by evanbiederstedt** [comment]
I tried jumping down the rabbit hole of changing everything to log10---it becomes tricky, as some of the base R stats functions use log. 

I'm happy just changing the plot axes as well.

**Comment by pkharchenko** [comment]
Not sure why there was a problem moving the plot to log10 - it should've been a simple scaling. 
I suggest that you leave the issue open and at some point I'll get to it and fix the plots.

**Comment by pkharchenko** [comment]
The commits look fine. Do the plots look consistent? If so, let's merge!

**Comment by evanbiederstedt** [comment]
The plots look consistent to me, based on the walkthrough. So, merging away!

**Pull request merged**
